version: 2.1
orbs:
  pod: pod/pod@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  install-for-root-test:
    description: Check pod install working in root.
    working_directory: ~/project/test-app
    macos:
      xcode: 13.4.1
    steps:
      - checkout:
          path: ~/project
      - pod/install

  install-for-subfolder-test:
    description: Check pod install working in subfolder.
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - pod/install:
          project-directory: ./test-app

workflows:
  test-deploy:
    jobs:
      - install-for-root-test:
          filters: *filters
      - install-for-subfolder-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: pod/pod
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - install-for-root-test
            - install-for-subfolder-test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
