description: >
  For more complex environment, we highly recommend using environment as a code approach.
  This will guarantee the same result on each computer.

usage:
  version: 2.1
  orbs:
    pod: xxkrashxx/pod@1.1.1

jobs:
  bundler-usage:
    steps:
      - checkout
      - pod/install:
          with-bundler: true
